---
appsecret: 78350218f4cf17b9c1024bd85d942518
spectoken: 83050114704e61f1c58d81d9b607baaf
securityheaders:
  Access-Control-Allow-Headers: 'Content-Type, X-CSRF-Token, X-Auth-Token'
  Access-Control-Allow-Methods: 'GET, POST'
  Access-Control-Allow-Origin: '*'
  Access-Control-Max-Age: 1728000
  #Content-Security-Policy: "default-src http: data: 'unsafe-inline' 'unsafe-eval'"
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-Xss-Protection: 1; mode=block
debug: false
redis:
  host: 10.220.154.179
  port: 6379
