apiVersion: apps/v1
kind: Deployment
metadata:
  name: igate-announce
  labels:
    app: igate-announce
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: igate-announce
  template:
    metadata:
      labels:
        app: igate-announce
    spec:
      containers:
        - image: gcr.io/customer-mol/lora-aprs-gateway/igate-announce-image
          name: igate-announce
          livenessProbe:
            exec:
              command:
              - /app/healthcheck
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 512Mi
              memory: 512Mi
